// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db.proto

package dbrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfo struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Coin                 uint64   `protobuf:"varint,2,opt,name=coin,proto3" json:"coin,omitempty"`
	Diamond              uint64   `protobuf:"varint,3,opt,name=diamond,proto3" json:"diamond,omitempty"`
	WinCount             uint32   `protobuf:"varint,4,opt,name=winCount,proto3" json:"winCount,omitempty"`
	AllCount             uint32   `protobuf:"varint,5,opt,name=allCount,proto3" json:"allCount,omitempty"`
	Avatar               string   `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Nick                 string   `protobuf:"bytes,7,opt,name=nick,proto3" json:"nick,omitempty"`
	Cup                  uint32   `protobuf:"varint,8,opt,name=cup,proto3" json:"cup,omitempty"`
	SK                   string   `protobuf:"bytes,9,opt,name=SK,proto3" json:"SK,omitempty"`
	VK                   uint32   `protobuf:"varint,10,opt,name=VK,proto3" json:"VK,omitempty"`
	Exp                  uint32   `protobuf:"varint,11,opt,name=exp,proto3" json:"exp,omitempty"`
	Gender               int32    `protobuf:"varint,12,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UserInfo) GetCoin() uint64 {
	if m != nil {
		return m.Coin
	}
	return 0
}

func (m *UserInfo) GetDiamond() uint64 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

func (m *UserInfo) GetWinCount() uint32 {
	if m != nil {
		return m.WinCount
	}
	return 0
}

func (m *UserInfo) GetAllCount() uint32 {
	if m != nil {
		return m.AllCount
	}
	return 0
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *UserInfo) GetCup() uint32 {
	if m != nil {
		return m.Cup
	}
	return 0
}

func (m *UserInfo) GetSK() string {
	if m != nil {
		return m.SK
	}
	return ""
}

func (m *UserInfo) GetVK() uint32 {
	if m != nil {
		return m.VK
	}
	return 0
}

func (m *UserInfo) GetExp() uint32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *UserInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

type CompUserInfo struct {
	Level                uint32   `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	MaxLevel             uint32   `protobuf:"varint,2,opt,name=maxLevel,proto3" json:"maxLevel,omitempty"`
	WinCount             uint32   `protobuf:"varint,3,opt,name=winCount,proto3" json:"winCount,omitempty"`
	AllCount             uint32   `protobuf:"varint,4,opt,name=allCount,proto3" json:"allCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompUserInfo) Reset()         { *m = CompUserInfo{} }
func (m *CompUserInfo) String() string { return proto.CompactTextString(m) }
func (*CompUserInfo) ProtoMessage()    {}
func (*CompUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{1}
}

func (m *CompUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompUserInfo.Unmarshal(m, b)
}
func (m *CompUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompUserInfo.Marshal(b, m, deterministic)
}
func (m *CompUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompUserInfo.Merge(m, src)
}
func (m *CompUserInfo) XXX_Size() int {
	return xxx_messageInfo_CompUserInfo.Size(m)
}
func (m *CompUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CompUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CompUserInfo proto.InternalMessageInfo

func (m *CompUserInfo) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *CompUserInfo) GetMaxLevel() uint32 {
	if m != nil {
		return m.MaxLevel
	}
	return 0
}

func (m *CompUserInfo) GetWinCount() uint32 {
	if m != nil {
		return m.WinCount
	}
	return 0
}

func (m *CompUserInfo) GetAllCount() uint32 {
	if m != nil {
		return m.AllCount
	}
	return 0
}

type UserInfoReq struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoReq) Reset()         { *m = UserInfoReq{} }
func (m *UserInfoReq) String() string { return proto.CompactTextString(m) }
func (*UserInfoReq) ProtoMessage()    {}
func (*UserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{2}
}

func (m *UserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoReq.Unmarshal(m, b)
}
func (m *UserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoReq.Marshal(b, m, deterministic)
}
func (m *UserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoReq.Merge(m, src)
}
func (m *UserInfoReq) XXX_Size() int {
	return xxx_messageInfo_UserInfoReq.Size(m)
}
func (m *UserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoReq proto.InternalMessageInfo

func (m *UserInfoReq) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type UserInfoRes struct {
	Code                 uint32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Info                 *UserInfo `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserInfoRes) Reset()         { *m = UserInfoRes{} }
func (m *UserInfoRes) String() string { return proto.CompactTextString(m) }
func (*UserInfoRes) ProtoMessage()    {}
func (*UserInfoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{3}
}

func (m *UserInfoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRes.Unmarshal(m, b)
}
func (m *UserInfoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRes.Marshal(b, m, deterministic)
}
func (m *UserInfoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRes.Merge(m, src)
}
func (m *UserInfoRes) XXX_Size() int {
	return xxx_messageInfo_UserInfoRes.Size(m)
}
func (m *UserInfoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRes proto.InternalMessageInfo

func (m *UserInfoRes) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserInfoRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *UserInfoRes) GetInfo() *UserInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type CompUserInfoReq struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompUserInfoReq) Reset()         { *m = CompUserInfoReq{} }
func (m *CompUserInfoReq) String() string { return proto.CompactTextString(m) }
func (*CompUserInfoReq) ProtoMessage()    {}
func (*CompUserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{4}
}

func (m *CompUserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompUserInfoReq.Unmarshal(m, b)
}
func (m *CompUserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompUserInfoReq.Marshal(b, m, deterministic)
}
func (m *CompUserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompUserInfoReq.Merge(m, src)
}
func (m *CompUserInfoReq) XXX_Size() int {
	return xxx_messageInfo_CompUserInfoReq.Size(m)
}
func (m *CompUserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CompUserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_CompUserInfoReq proto.InternalMessageInfo

func (m *CompUserInfoReq) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type CompUserInfoRes struct {
	Code                 uint32        `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Info                 *CompUserInfo `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CompUserInfoRes) Reset()         { *m = CompUserInfoRes{} }
func (m *CompUserInfoRes) String() string { return proto.CompactTextString(m) }
func (*CompUserInfoRes) ProtoMessage()    {}
func (*CompUserInfoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{5}
}

func (m *CompUserInfoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompUserInfoRes.Unmarshal(m, b)
}
func (m *CompUserInfoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompUserInfoRes.Marshal(b, m, deterministic)
}
func (m *CompUserInfoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompUserInfoRes.Merge(m, src)
}
func (m *CompUserInfoRes) XXX_Size() int {
	return xxx_messageInfo_CompUserInfoRes.Size(m)
}
func (m *CompUserInfoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CompUserInfoRes.DiscardUnknown(m)
}

var xxx_messageInfo_CompUserInfoRes proto.InternalMessageInfo

func (m *CompUserInfoRes) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CompUserInfoRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CompUserInfoRes) GetInfo() *CompUserInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type GameOverReq struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	OtherID              uint32   `protobuf:"varint,2,opt,name=otherID,proto3" json:"otherID,omitempty"`
	WinNum               uint32   `protobuf:"varint,3,opt,name=winNum,proto3" json:"winNum,omitempty"`
	OtherWinNum          uint32   `protobuf:"varint,4,opt,name=otherWinNum,proto3" json:"otherWinNum,omitempty"`
	Type                 uint32   `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Cup                  uint32   `protobuf:"varint,6,opt,name=cup,proto3" json:"cup,omitempty"`
	Exp                  uint32   `protobuf:"varint,7,opt,name=exp,proto3" json:"exp,omitempty"`
	Level                uint32   `protobuf:"varint,8,opt,name=level,proto3" json:"level,omitempty"`
	Coin                 uint64   `protobuf:"varint,9,opt,name=coin,proto3" json:"coin,omitempty"`
	Diamond              uint64   `protobuf:"varint,10,opt,name=diamond,proto3" json:"diamond,omitempty"`
	HeroID               uint32   `protobuf:"varint,11,opt,name=heroID,proto3" json:"heroID,omitempty"`
	OtherHeroID          uint32   `protobuf:"varint,12,opt,name=otherHeroID,proto3" json:"otherHeroID,omitempty"`
	CurrentLevel         uint32   `protobuf:"varint,13,opt,name=currentLevel,proto3" json:"currentLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameOverReq) Reset()         { *m = GameOverReq{} }
func (m *GameOverReq) String() string { return proto.CompactTextString(m) }
func (*GameOverReq) ProtoMessage()    {}
func (*GameOverReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{6}
}

func (m *GameOverReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameOverReq.Unmarshal(m, b)
}
func (m *GameOverReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameOverReq.Marshal(b, m, deterministic)
}
func (m *GameOverReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameOverReq.Merge(m, src)
}
func (m *GameOverReq) XXX_Size() int {
	return xxx_messageInfo_GameOverReq.Size(m)
}
func (m *GameOverReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GameOverReq.DiscardUnknown(m)
}

var xxx_messageInfo_GameOverReq proto.InternalMessageInfo

func (m *GameOverReq) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *GameOverReq) GetOtherID() uint32 {
	if m != nil {
		return m.OtherID
	}
	return 0
}

func (m *GameOverReq) GetWinNum() uint32 {
	if m != nil {
		return m.WinNum
	}
	return 0
}

func (m *GameOverReq) GetOtherWinNum() uint32 {
	if m != nil {
		return m.OtherWinNum
	}
	return 0
}

func (m *GameOverReq) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *GameOverReq) GetCup() uint32 {
	if m != nil {
		return m.Cup
	}
	return 0
}

func (m *GameOverReq) GetExp() uint32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *GameOverReq) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *GameOverReq) GetCoin() uint64 {
	if m != nil {
		return m.Coin
	}
	return 0
}

func (m *GameOverReq) GetDiamond() uint64 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

func (m *GameOverReq) GetHeroID() uint32 {
	if m != nil {
		return m.HeroID
	}
	return 0
}

func (m *GameOverReq) GetOtherHeroID() uint32 {
	if m != nil {
		return m.OtherHeroID
	}
	return 0
}

func (m *GameOverReq) GetCurrentLevel() uint32 {
	if m != nil {
		return m.CurrentLevel
	}
	return 0
}

type GameOverRes struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Status               uint32   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	RewardID             uint32   `protobuf:"varint,4,opt,name=rewardID,proto3" json:"rewardID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameOverRes) Reset()         { *m = GameOverRes{} }
func (m *GameOverRes) String() string { return proto.CompactTextString(m) }
func (*GameOverRes) ProtoMessage()    {}
func (*GameOverRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{7}
}

func (m *GameOverRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameOverRes.Unmarshal(m, b)
}
func (m *GameOverRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameOverRes.Marshal(b, m, deterministic)
}
func (m *GameOverRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameOverRes.Merge(m, src)
}
func (m *GameOverRes) XXX_Size() int {
	return xxx_messageInfo_GameOverRes.Size(m)
}
func (m *GameOverRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GameOverRes.DiscardUnknown(m)
}

var xxx_messageInfo_GameOverRes proto.InternalMessageInfo

func (m *GameOverRes) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GameOverRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GameOverRes) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GameOverRes) GetRewardID() uint32 {
	if m != nil {
		return m.RewardID
	}
	return 0
}

type BattleDailyTaskReq struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	WinNum               uint32   `protobuf:"varint,2,opt,name=winNum,proto3" json:"winNum,omitempty"`
	OtherWinNum          uint32   `protobuf:"varint,3,opt,name=otherWinNum,proto3" json:"otherWinNum,omitempty"`
	Type                 uint32   `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	HitHead              uint32   `protobuf:"varint,5,opt,name=hitHead,proto3" json:"hitHead,omitempty"`
	Sk                   string   `protobuf:"bytes,6,opt,name=sk,proto3" json:"sk,omitempty"`
	Vk                   uint32   `protobuf:"varint,7,opt,name=vk,proto3" json:"vk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BattleDailyTaskReq) Reset()         { *m = BattleDailyTaskReq{} }
func (m *BattleDailyTaskReq) String() string { return proto.CompactTextString(m) }
func (*BattleDailyTaskReq) ProtoMessage()    {}
func (*BattleDailyTaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{8}
}

func (m *BattleDailyTaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BattleDailyTaskReq.Unmarshal(m, b)
}
func (m *BattleDailyTaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BattleDailyTaskReq.Marshal(b, m, deterministic)
}
func (m *BattleDailyTaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BattleDailyTaskReq.Merge(m, src)
}
func (m *BattleDailyTaskReq) XXX_Size() int {
	return xxx_messageInfo_BattleDailyTaskReq.Size(m)
}
func (m *BattleDailyTaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BattleDailyTaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_BattleDailyTaskReq proto.InternalMessageInfo

func (m *BattleDailyTaskReq) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *BattleDailyTaskReq) GetWinNum() uint32 {
	if m != nil {
		return m.WinNum
	}
	return 0
}

func (m *BattleDailyTaskReq) GetOtherWinNum() uint32 {
	if m != nil {
		return m.OtherWinNum
	}
	return 0
}

func (m *BattleDailyTaskReq) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *BattleDailyTaskReq) GetHitHead() uint32 {
	if m != nil {
		return m.HitHead
	}
	return 0
}

func (m *BattleDailyTaskReq) GetSk() string {
	if m != nil {
		return m.Sk
	}
	return ""
}

func (m *BattleDailyTaskReq) GetVk() uint32 {
	if m != nil {
		return m.Vk
	}
	return 0
}

type BattleDailyTaskRes struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BattleDailyTaskRes) Reset()         { *m = BattleDailyTaskRes{} }
func (m *BattleDailyTaskRes) String() string { return proto.CompactTextString(m) }
func (*BattleDailyTaskRes) ProtoMessage()    {}
func (*BattleDailyTaskRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{9}
}

func (m *BattleDailyTaskRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BattleDailyTaskRes.Unmarshal(m, b)
}
func (m *BattleDailyTaskRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BattleDailyTaskRes.Marshal(b, m, deterministic)
}
func (m *BattleDailyTaskRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BattleDailyTaskRes.Merge(m, src)
}
func (m *BattleDailyTaskRes) XXX_Size() int {
	return xxx_messageInfo_BattleDailyTaskRes.Size(m)
}
func (m *BattleDailyTaskRes) XXX_DiscardUnknown() {
	xxx_messageInfo_BattleDailyTaskRes.DiscardUnknown(m)
}

var xxx_messageInfo_BattleDailyTaskRes proto.InternalMessageInfo

func (m *BattleDailyTaskRes) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BattleDailyTaskRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "dbrpc.UserInfo")
	proto.RegisterType((*CompUserInfo)(nil), "dbrpc.CompUserInfo")
	proto.RegisterType((*UserInfoReq)(nil), "dbrpc.UserInfoReq")
	proto.RegisterType((*UserInfoRes)(nil), "dbrpc.UserInfoRes")
	proto.RegisterType((*CompUserInfoReq)(nil), "dbrpc.CompUserInfoReq")
	proto.RegisterType((*CompUserInfoRes)(nil), "dbrpc.CompUserInfoRes")
	proto.RegisterType((*GameOverReq)(nil), "dbrpc.GameOverReq")
	proto.RegisterType((*GameOverRes)(nil), "dbrpc.GameOverRes")
	proto.RegisterType((*BattleDailyTaskReq)(nil), "dbrpc.BattleDailyTaskReq")
	proto.RegisterType((*BattleDailyTaskRes)(nil), "dbrpc.BattleDailyTaskRes")
}

func init() { proto.RegisterFile("db.proto", fileDescriptor_8817812184a13374) }

var fileDescriptor_8817812184a13374 = []byte{
	// 635 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcb, 0x6e, 0xd3, 0x4c,
	0x14, 0x6e, 0x9c, 0xfb, 0x71, 0xfa, 0xe7, 0xd7, 0x80, 0xa2, 0x21, 0x12, 0x52, 0x30, 0x0b, 0xb2,
	0xea, 0xa2, 0x20, 0x21, 0xb1, 0x6c, 0x2c, 0xb5, 0x56, 0x10, 0x20, 0x17, 0x0a, 0x4b, 0xa6, 0xf1,
	0xb4, 0xb5, 0x7c, 0xed, 0x78, 0x92, 0xa6, 0x2f, 0x80, 0x78, 0x18, 0xde, 0x84, 0x97, 0x42, 0x73,
	0x73, 0xed, 0xd4, 0xad, 0xba, 0x9b, 0xef, 0x9c, 0xe3, 0x39, 0x97, 0xef, 0x3b, 0x63, 0x18, 0x04,
	0xe7, 0x07, 0x39, 0xcb, 0x78, 0x86, 0xba, 0xc1, 0x39, 0xcb, 0x57, 0xce, 0x6f, 0x0b, 0x06, 0xdf,
	0x0a, 0xca, 0xbc, 0xf4, 0x22, 0x43, 0xff, 0x81, 0xe5, 0xb9, 0xb8, 0x35, 0x6b, 0xcd, 0xf7, 0x7d,
	0xcb, 0x73, 0x11, 0x82, 0xce, 0x2a, 0x0b, 0x53, 0x6c, 0xcd, 0x5a, 0xf3, 0x8e, 0x2f, 0xcf, 0x08,
	0x43, 0x3f, 0x08, 0x49, 0x92, 0xa5, 0x01, 0x6e, 0x4b, 0xb3, 0x81, 0x68, 0x0a, 0x83, 0x9b, 0x30,
	0x5d, 0x64, 0xeb, 0x94, 0xe3, 0x8e, 0xbc, 0xa3, 0xc4, 0xc2, 0x47, 0xe2, 0x58, 0xf9, 0xba, 0xca,
	0x67, 0x30, 0x9a, 0x40, 0x8f, 0x6c, 0x08, 0x27, 0x0c, 0xf7, 0x66, 0xad, 0xf9, 0xd0, 0xd7, 0x48,
	0x64, 0x4f, 0xc3, 0x55, 0x84, 0xfb, 0xd2, 0x2a, 0xcf, 0xe8, 0x7f, 0x68, 0xaf, 0xd6, 0x39, 0x1e,
	0xc8, 0x2b, 0xc4, 0x51, 0xd4, 0x7c, 0xba, 0xc4, 0x43, 0x19, 0x63, 0x9d, 0x2e, 0x05, 0x3e, 0x5b,
	0x62, 0x50, 0x3d, 0x9c, 0x2d, 0xc5, 0x17, 0x74, 0x9b, 0x63, 0x5b, 0x7d, 0x41, 0xb7, 0xb9, 0xc8,
	0x77, 0x49, 0xd3, 0x80, 0x32, 0x3c, 0x9a, 0xb5, 0xe6, 0x5d, 0x5f, 0x23, 0x67, 0x0b, 0xa3, 0x45,
	0x96, 0xe4, 0xe5, 0x34, 0x9e, 0x43, 0x37, 0xa6, 0x1b, 0x1a, 0xeb, 0x81, 0x28, 0x20, 0x3a, 0x49,
	0xc8, 0xf6, 0xa3, 0x74, 0x58, 0xaa, 0x13, 0x83, 0x6b, 0x13, 0x68, 0x3f, 0x32, 0x81, 0x4e, 0x7d,
	0x02, 0xce, 0x4b, 0xb0, 0x4d, 0x56, 0x9f, 0x5e, 0xef, 0xd2, 0xe0, 0xfc, 0xa8, 0xba, 0x0b, 0xc5,
	0x4a, 0x40, 0x75, 0x80, 0x3c, 0x8b, 0x2e, 0x93, 0xe2, 0x52, 0x16, 0x34, 0xf4, 0xc5, 0x11, 0xbd,
	0x86, 0x4e, 0x98, 0x5e, 0x64, 0xb2, 0x0e, 0xfb, 0x70, 0x7c, 0x20, 0xe9, 0x3e, 0x28, 0xef, 0x91,
	0x4e, 0xe7, 0x15, 0x8c, 0xab, 0x2d, 0x37, 0x25, 0xff, 0xb9, 0x1b, 0xf2, 0xd4, 0x02, 0xde, 0xd4,
	0x0a, 0x78, 0xa6, 0x0b, 0xa8, 0xdd, 0xa5, 0x8a, 0xf8, 0x6b, 0x81, 0x7d, 0x4c, 0x12, 0xfa, 0x79,
	0x43, 0x59, 0x43, 0x05, 0x42, 0x71, 0x19, 0xbf, 0xa2, 0xcc, 0x73, 0xf5, 0xc0, 0x0d, 0x14, 0x4c,
	0xde, 0x84, 0xe9, 0xa7, 0x75, 0xa2, 0xa7, 0xad, 0x11, 0x9a, 0x81, 0x2d, 0x43, 0xbe, 0x2b, 0xa7,
	0x1a, 0x77, 0xd5, 0x24, 0x5a, 0xe0, 0xb7, 0x39, 0xd5, 0x5a, 0x94, 0x67, 0xa3, 0xad, 0xde, 0x9d,
	0xb6, 0xb4, 0x76, 0xfa, 0x77, 0xda, 0x29, 0x35, 0x31, 0xa8, 0x6a, 0xc2, 0xec, 0xc9, 0xb0, 0x79,
	0x4f, 0xa0, 0xbe, 0x27, 0x13, 0xe8, 0x5d, 0x51, 0x96, 0x79, 0xae, 0x16, 0xa5, 0x46, 0x65, 0xd5,
	0x27, 0xca, 0x39, 0xaa, 0x54, 0xad, 0x4c, 0xc8, 0x81, 0xd1, 0x6a, 0xcd, 0x18, 0x4d, 0xb9, 0xd2,
	0xdf, 0xbe, 0x0c, 0xa9, 0xd9, 0x9c, 0xcb, 0xea, 0x30, 0x9f, 0xca, 0xd5, 0x04, 0x7a, 0x05, 0x27,
	0x7c, 0x5d, 0x98, 0x41, 0x2a, 0x24, 0x44, 0xcb, 0xe8, 0x0d, 0x61, 0x81, 0xe7, 0x1a, 0xd1, 0x1a,
	0xec, 0xfc, 0x69, 0x01, 0x3a, 0x22, 0x9c, 0xc7, 0xd4, 0x25, 0x61, 0x7c, 0xfb, 0x95, 0x14, 0x51,
	0x13, 0x7b, 0x77, 0x1c, 0x59, 0x8f, 0x71, 0xd4, 0x7e, 0x98, 0xa3, 0x4e, 0x85, 0x23, 0x0c, 0xfd,
	0xab, 0x90, 0x9f, 0x50, 0x12, 0x68, 0xea, 0x0c, 0x14, 0x79, 0x8b, 0x48, 0xbf, 0x20, 0x56, 0x11,
	0x09, 0xbc, 0x89, 0x34, 0x75, 0xd6, 0x26, 0x72, 0x3e, 0x34, 0x54, 0xfb, 0xc4, 0xf1, 0x1c, 0xfe,
	0xb2, 0xa0, 0xeb, 0x1e, 0xf9, 0x5f, 0x16, 0xe8, 0x3d, 0xd8, 0xc7, 0x94, 0x97, 0x4f, 0x04, 0xda,
	0x5d, 0x2b, 0x7a, 0x3d, 0xbd, 0x6f, 0x2b, 0x9c, 0x3d, 0xb4, 0x80, 0xf1, 0x31, 0xe5, 0xb5, 0xf7,
	0x65, 0xd2, 0xb4, 0x12, 0xf4, 0x7a, 0xda, 0x6c, 0x17, 0x97, 0xbc, 0x83, 0x81, 0xe1, 0xb6, 0x4c,
	0x5d, 0xd9, 0x9c, 0xe9, 0x7d, 0x9b, 0xf8, 0xca, 0x83, 0xf1, 0x4e, 0xe7, 0xe8, 0x85, 0x0e, 0xbc,
	0xcf, 0xdf, 0xf4, 0x41, 0x57, 0xe1, 0xec, 0x9d, 0xf7, 0xe4, 0xbf, 0xe3, 0xed, 0xbf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x11, 0xe0, 0xc7, 0x29, 0x47, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DBRPCClient is the client API for DBRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DBRPCClient interface {
	GetUserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoRes, error)
	GetCompUserInfo(ctx context.Context, in *CompUserInfoReq, opts ...grpc.CallOption) (*CompUserInfoRes, error)
	GameOver(ctx context.Context, in *GameOverReq, opts ...grpc.CallOption) (*GameOverRes, error)
	BattleDailyTask(ctx context.Context, in *BattleDailyTaskReq, opts ...grpc.CallOption) (*BattleDailyTaskRes, error)
}

type dBRPCClient struct {
	cc *grpc.ClientConn
}

func NewDBRPCClient(cc *grpc.ClientConn) DBRPCClient {
	return &dBRPCClient{cc}
}

func (c *dBRPCClient) GetUserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoRes, error) {
	out := new(UserInfoRes)
	err := c.cc.Invoke(ctx, "/dbrpc.DBRPC/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBRPCClient) GetCompUserInfo(ctx context.Context, in *CompUserInfoReq, opts ...grpc.CallOption) (*CompUserInfoRes, error) {
	out := new(CompUserInfoRes)
	err := c.cc.Invoke(ctx, "/dbrpc.DBRPC/GetCompUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBRPCClient) GameOver(ctx context.Context, in *GameOverReq, opts ...grpc.CallOption) (*GameOverRes, error) {
	out := new(GameOverRes)
	err := c.cc.Invoke(ctx, "/dbrpc.DBRPC/GameOver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBRPCClient) BattleDailyTask(ctx context.Context, in *BattleDailyTaskReq, opts ...grpc.CallOption) (*BattleDailyTaskRes, error) {
	out := new(BattleDailyTaskRes)
	err := c.cc.Invoke(ctx, "/dbrpc.DBRPC/BattleDailyTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBRPCServer is the server API for DBRPC service.
type DBRPCServer interface {
	GetUserInfo(context.Context, *UserInfoReq) (*UserInfoRes, error)
	GetCompUserInfo(context.Context, *CompUserInfoReq) (*CompUserInfoRes, error)
	GameOver(context.Context, *GameOverReq) (*GameOverRes, error)
	BattleDailyTask(context.Context, *BattleDailyTaskReq) (*BattleDailyTaskRes, error)
}

// UnimplementedDBRPCServer can be embedded to have forward compatible implementations.
type UnimplementedDBRPCServer struct {
}

func (*UnimplementedDBRPCServer) GetUserInfo(ctx context.Context, req *UserInfoReq) (*UserInfoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (*UnimplementedDBRPCServer) GetCompUserInfo(ctx context.Context, req *CompUserInfoReq) (*CompUserInfoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompUserInfo not implemented")
}
func (*UnimplementedDBRPCServer) GameOver(ctx context.Context, req *GameOverReq) (*GameOverRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GameOver not implemented")
}
func (*UnimplementedDBRPCServer) BattleDailyTask(ctx context.Context, req *BattleDailyTaskReq) (*BattleDailyTaskRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BattleDailyTask not implemented")
}

func RegisterDBRPCServer(s *grpc.Server, srv DBRPCServer) {
	s.RegisterService(&_DBRPC_serviceDesc, srv)
}

func _DBRPC_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBRPCServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbrpc.DBRPC/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBRPCServer).GetUserInfo(ctx, req.(*UserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBRPC_GetCompUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBRPCServer).GetCompUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbrpc.DBRPC/GetCompUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBRPCServer).GetCompUserInfo(ctx, req.(*CompUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBRPC_GameOver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameOverReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBRPCServer).GameOver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbrpc.DBRPC/GameOver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBRPCServer).GameOver(ctx, req.(*GameOverReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBRPC_BattleDailyTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BattleDailyTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBRPCServer).BattleDailyTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbrpc.DBRPC/BattleDailyTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBRPCServer).BattleDailyTask(ctx, req.(*BattleDailyTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DBRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dbrpc.DBRPC",
	HandlerType: (*DBRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _DBRPC_GetUserInfo_Handler,
		},
		{
			MethodName: "GetCompUserInfo",
			Handler:    _DBRPC_GetCompUserInfo_Handler,
		},
		{
			MethodName: "GameOver",
			Handler:    _DBRPC_GameOver_Handler,
		},
		{
			MethodName: "BattleDailyTask",
			Handler:    _DBRPC_BattleDailyTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "db.proto",
}
