// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jb.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MoveUp struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PositionX            float32  `protobuf:"fixed32,2,opt,name=PositionX,proto3" json:"PositionX,omitempty"`
	PositionY            float32  `protobuf:"fixed32,3,opt,name=PositionY,proto3" json:"PositionY,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveUp) Reset()         { *m = MoveUp{} }
func (m *MoveUp) String() string { return proto.CompactTextString(m) }
func (*MoveUp) ProtoMessage()    {}
func (*MoveUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c0408b81072356a, []int{0}
}

func (m *MoveUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveUp.Unmarshal(m, b)
}
func (m *MoveUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveUp.Marshal(b, m, deterministic)
}
func (m *MoveUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveUp.Merge(m, src)
}
func (m *MoveUp) XXX_Size() int {
	return xxx_messageInfo_MoveUp.Size(m)
}
func (m *MoveUp) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveUp.DiscardUnknown(m)
}

var xxx_messageInfo_MoveUp proto.InternalMessageInfo

func (m *MoveUp) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *MoveUp) GetPositionX() float32 {
	if m != nil {
		return m.PositionX
	}
	return 0
}

func (m *MoveUp) GetPositionY() float32 {
	if m != nil {
		return m.PositionY
	}
	return 0
}

type MoveDown struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PositionX            float32  `protobuf:"fixed32,2,opt,name=PositionX,proto3" json:"PositionX,omitempty"`
	PositionY            float32  `protobuf:"fixed32,3,opt,name=PositionY,proto3" json:"PositionY,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveDown) Reset()         { *m = MoveDown{} }
func (m *MoveDown) String() string { return proto.CompactTextString(m) }
func (*MoveDown) ProtoMessage()    {}
func (*MoveDown) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c0408b81072356a, []int{1}
}

func (m *MoveDown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveDown.Unmarshal(m, b)
}
func (m *MoveDown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveDown.Marshal(b, m, deterministic)
}
func (m *MoveDown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveDown.Merge(m, src)
}
func (m *MoveDown) XXX_Size() int {
	return xxx_messageInfo_MoveDown.Size(m)
}
func (m *MoveDown) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveDown.DiscardUnknown(m)
}

var xxx_messageInfo_MoveDown proto.InternalMessageInfo

func (m *MoveDown) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *MoveDown) GetPositionX() float32 {
	if m != nil {
		return m.PositionX
	}
	return 0
}

func (m *MoveDown) GetPositionY() float32 {
	if m != nil {
		return m.PositionY
	}
	return 0
}

type MoveDownOver struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PositionX            float32  `protobuf:"fixed32,2,opt,name=PositionX,proto3" json:"PositionX,omitempty"`
	PositionY            float32  `protobuf:"fixed32,3,opt,name=PositionY,proto3" json:"PositionY,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveDownOver) Reset()         { *m = MoveDownOver{} }
func (m *MoveDownOver) String() string { return proto.CompactTextString(m) }
func (*MoveDownOver) ProtoMessage()    {}
func (*MoveDownOver) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c0408b81072356a, []int{2}
}

func (m *MoveDownOver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveDownOver.Unmarshal(m, b)
}
func (m *MoveDownOver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveDownOver.Marshal(b, m, deterministic)
}
func (m *MoveDownOver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveDownOver.Merge(m, src)
}
func (m *MoveDownOver) XXX_Size() int {
	return xxx_messageInfo_MoveDownOver.Size(m)
}
func (m *MoveDownOver) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveDownOver.DiscardUnknown(m)
}

var xxx_messageInfo_MoveDownOver proto.InternalMessageInfo

func (m *MoveDownOver) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *MoveDownOver) GetPositionX() float32 {
	if m != nil {
		return m.PositionX
	}
	return 0
}

func (m *MoveDownOver) GetPositionY() float32 {
	if m != nil {
		return m.PositionY
	}
	return 0
}

type MoveLeft struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PositionX            float32  `protobuf:"fixed32,2,opt,name=PositionX,proto3" json:"PositionX,omitempty"`
	PositionY            float32  `protobuf:"fixed32,3,opt,name=PositionY,proto3" json:"PositionY,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveLeft) Reset()         { *m = MoveLeft{} }
func (m *MoveLeft) String() string { return proto.CompactTextString(m) }
func (*MoveLeft) ProtoMessage()    {}
func (*MoveLeft) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c0408b81072356a, []int{3}
}

func (m *MoveLeft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveLeft.Unmarshal(m, b)
}
func (m *MoveLeft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveLeft.Marshal(b, m, deterministic)
}
func (m *MoveLeft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveLeft.Merge(m, src)
}
func (m *MoveLeft) XXX_Size() int {
	return xxx_messageInfo_MoveLeft.Size(m)
}
func (m *MoveLeft) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveLeft.DiscardUnknown(m)
}

var xxx_messageInfo_MoveLeft proto.InternalMessageInfo

func (m *MoveLeft) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *MoveLeft) GetPositionX() float32 {
	if m != nil {
		return m.PositionX
	}
	return 0
}

func (m *MoveLeft) GetPositionY() float32 {
	if m != nil {
		return m.PositionY
	}
	return 0
}

type MoveLeftOver struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PositionX            float32  `protobuf:"fixed32,2,opt,name=PositionX,proto3" json:"PositionX,omitempty"`
	PositionY            float32  `protobuf:"fixed32,3,opt,name=PositionY,proto3" json:"PositionY,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveLeftOver) Reset()         { *m = MoveLeftOver{} }
func (m *MoveLeftOver) String() string { return proto.CompactTextString(m) }
func (*MoveLeftOver) ProtoMessage()    {}
func (*MoveLeftOver) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c0408b81072356a, []int{4}
}

func (m *MoveLeftOver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveLeftOver.Unmarshal(m, b)
}
func (m *MoveLeftOver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveLeftOver.Marshal(b, m, deterministic)
}
func (m *MoveLeftOver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveLeftOver.Merge(m, src)
}
func (m *MoveLeftOver) XXX_Size() int {
	return xxx_messageInfo_MoveLeftOver.Size(m)
}
func (m *MoveLeftOver) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveLeftOver.DiscardUnknown(m)
}

var xxx_messageInfo_MoveLeftOver proto.InternalMessageInfo

func (m *MoveLeftOver) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *MoveLeftOver) GetPositionX() float32 {
	if m != nil {
		return m.PositionX
	}
	return 0
}

func (m *MoveLeftOver) GetPositionY() float32 {
	if m != nil {
		return m.PositionY
	}
	return 0
}

type MoveRight struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PositionX            float32  `protobuf:"fixed32,2,opt,name=PositionX,proto3" json:"PositionX,omitempty"`
	PositionY            float32  `protobuf:"fixed32,3,opt,name=PositionY,proto3" json:"PositionY,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveRight) Reset()         { *m = MoveRight{} }
func (m *MoveRight) String() string { return proto.CompactTextString(m) }
func (*MoveRight) ProtoMessage()    {}
func (*MoveRight) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c0408b81072356a, []int{5}
}

func (m *MoveRight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveRight.Unmarshal(m, b)
}
func (m *MoveRight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveRight.Marshal(b, m, deterministic)
}
func (m *MoveRight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveRight.Merge(m, src)
}
func (m *MoveRight) XXX_Size() int {
	return xxx_messageInfo_MoveRight.Size(m)
}
func (m *MoveRight) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveRight.DiscardUnknown(m)
}

var xxx_messageInfo_MoveRight proto.InternalMessageInfo

func (m *MoveRight) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *MoveRight) GetPositionX() float32 {
	if m != nil {
		return m.PositionX
	}
	return 0
}

func (m *MoveRight) GetPositionY() float32 {
	if m != nil {
		return m.PositionY
	}
	return 0
}

type MoveRightOver struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PositionX            float32  `protobuf:"fixed32,2,opt,name=PositionX,proto3" json:"PositionX,omitempty"`
	PositionY            float32  `protobuf:"fixed32,3,opt,name=PositionY,proto3" json:"PositionY,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveRightOver) Reset()         { *m = MoveRightOver{} }
func (m *MoveRightOver) String() string { return proto.CompactTextString(m) }
func (*MoveRightOver) ProtoMessage()    {}
func (*MoveRightOver) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c0408b81072356a, []int{6}
}

func (m *MoveRightOver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveRightOver.Unmarshal(m, b)
}
func (m *MoveRightOver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveRightOver.Marshal(b, m, deterministic)
}
func (m *MoveRightOver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveRightOver.Merge(m, src)
}
func (m *MoveRightOver) XXX_Size() int {
	return xxx_messageInfo_MoveRightOver.Size(m)
}
func (m *MoveRightOver) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveRightOver.DiscardUnknown(m)
}

var xxx_messageInfo_MoveRightOver proto.InternalMessageInfo

func (m *MoveRightOver) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *MoveRightOver) GetPositionX() float32 {
	if m != nil {
		return m.PositionX
	}
	return 0
}

func (m *MoveRightOver) GetPositionY() float32 {
	if m != nil {
		return m.PositionY
	}
	return 0
}

type Fall struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PositionX            float32  `protobuf:"fixed32,2,opt,name=PositionX,proto3" json:"PositionX,omitempty"`
	PositionY            float32  `protobuf:"fixed32,3,opt,name=PositionY,proto3" json:"PositionY,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fall) Reset()         { *m = Fall{} }
func (m *Fall) String() string { return proto.CompactTextString(m) }
func (*Fall) ProtoMessage()    {}
func (*Fall) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c0408b81072356a, []int{7}
}

func (m *Fall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fall.Unmarshal(m, b)
}
func (m *Fall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fall.Marshal(b, m, deterministic)
}
func (m *Fall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fall.Merge(m, src)
}
func (m *Fall) XXX_Size() int {
	return xxx_messageInfo_Fall.Size(m)
}
func (m *Fall) XXX_DiscardUnknown() {
	xxx_messageInfo_Fall.DiscardUnknown(m)
}

var xxx_messageInfo_Fall proto.InternalMessageInfo

func (m *Fall) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Fall) GetPositionX() float32 {
	if m != nil {
		return m.PositionX
	}
	return 0
}

func (m *Fall) GetPositionY() float32 {
	if m != nil {
		return m.PositionY
	}
	return 0
}

type Die struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PositionX            float32  `protobuf:"fixed32,2,opt,name=PositionX,proto3" json:"PositionX,omitempty"`
	PositionY            float32  `protobuf:"fixed32,3,opt,name=PositionY,proto3" json:"PositionY,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Die) Reset()         { *m = Die{} }
func (m *Die) String() string { return proto.CompactTextString(m) }
func (*Die) ProtoMessage()    {}
func (*Die) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c0408b81072356a, []int{8}
}

func (m *Die) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Die.Unmarshal(m, b)
}
func (m *Die) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Die.Marshal(b, m, deterministic)
}
func (m *Die) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Die.Merge(m, src)
}
func (m *Die) XXX_Size() int {
	return xxx_messageInfo_Die.Size(m)
}
func (m *Die) XXX_DiscardUnknown() {
	xxx_messageInfo_Die.DiscardUnknown(m)
}

var xxx_messageInfo_Die proto.InternalMessageInfo

func (m *Die) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Die) GetPositionX() float32 {
	if m != nil {
		return m.PositionX
	}
	return 0
}

func (m *Die) GetPositionY() float32 {
	if m != nil {
		return m.PositionY
	}
	return 0
}

type Idle struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PositionX            float32  `protobuf:"fixed32,2,opt,name=PositionX,proto3" json:"PositionX,omitempty"`
	PositionY            float32  `protobuf:"fixed32,3,opt,name=PositionY,proto3" json:"PositionY,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Idle) Reset()         { *m = Idle{} }
func (m *Idle) String() string { return proto.CompactTextString(m) }
func (*Idle) ProtoMessage()    {}
func (*Idle) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c0408b81072356a, []int{9}
}

func (m *Idle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Idle.Unmarshal(m, b)
}
func (m *Idle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Idle.Marshal(b, m, deterministic)
}
func (m *Idle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Idle.Merge(m, src)
}
func (m *Idle) XXX_Size() int {
	return xxx_messageInfo_Idle.Size(m)
}
func (m *Idle) XXX_DiscardUnknown() {
	xxx_messageInfo_Idle.DiscardUnknown(m)
}

var xxx_messageInfo_Idle proto.InternalMessageInfo

func (m *Idle) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Idle) GetPositionX() float32 {
	if m != nil {
		return m.PositionX
	}
	return 0
}

func (m *Idle) GetPositionY() float32 {
	if m != nil {
		return m.PositionY
	}
	return 0
}

type Bounce struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PositionX            float32  `protobuf:"fixed32,2,opt,name=PositionX,proto3" json:"PositionX,omitempty"`
	PositionY            float32  `protobuf:"fixed32,3,opt,name=PositionY,proto3" json:"PositionY,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bounce) Reset()         { *m = Bounce{} }
func (m *Bounce) String() string { return proto.CompactTextString(m) }
func (*Bounce) ProtoMessage()    {}
func (*Bounce) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c0408b81072356a, []int{10}
}

func (m *Bounce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bounce.Unmarshal(m, b)
}
func (m *Bounce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bounce.Marshal(b, m, deterministic)
}
func (m *Bounce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bounce.Merge(m, src)
}
func (m *Bounce) XXX_Size() int {
	return xxx_messageInfo_Bounce.Size(m)
}
func (m *Bounce) XXX_DiscardUnknown() {
	xxx_messageInfo_Bounce.DiscardUnknown(m)
}

var xxx_messageInfo_Bounce proto.InternalMessageInfo

func (m *Bounce) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Bounce) GetPositionX() float32 {
	if m != nil {
		return m.PositionX
	}
	return 0
}

func (m *Bounce) GetPositionY() float32 {
	if m != nil {
		return m.PositionY
	}
	return 0
}

type Props struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Props) Reset()         { *m = Props{} }
func (m *Props) String() string { return proto.CompactTextString(m) }
func (*Props) ProtoMessage()    {}
func (*Props) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c0408b81072356a, []int{11}
}

func (m *Props) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Props.Unmarshal(m, b)
}
func (m *Props) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Props.Marshal(b, m, deterministic)
}
func (m *Props) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Props.Merge(m, src)
}
func (m *Props) XXX_Size() int {
	return xxx_messageInfo_Props.Size(m)
}
func (m *Props) XXX_DiscardUnknown() {
	xxx_messageInfo_Props.DiscardUnknown(m)
}

var xxx_messageInfo_Props proto.InternalMessageInfo

func (m *Props) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Props) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Props) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type FootBoard struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FootBoard) Reset()         { *m = FootBoard{} }
func (m *FootBoard) String() string { return proto.CompactTextString(m) }
func (*FootBoard) ProtoMessage()    {}
func (*FootBoard) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c0408b81072356a, []int{12}
}

func (m *FootBoard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FootBoard.Unmarshal(m, b)
}
func (m *FootBoard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FootBoard.Marshal(b, m, deterministic)
}
func (m *FootBoard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FootBoard.Merge(m, src)
}
func (m *FootBoard) XXX_Size() int {
	return xxx_messageInfo_FootBoard.Size(m)
}
func (m *FootBoard) XXX_DiscardUnknown() {
	xxx_messageInfo_FootBoard.DiscardUnknown(m)
}

var xxx_messageInfo_FootBoard proto.InternalMessageInfo

func (m *FootBoard) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *FootBoard) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *FootBoard) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Action struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	J                    string   `protobuf:"bytes,2,opt,name=J,proto3" json:"J,omitempty"`
	K                    string   `protobuf:"bytes,3,opt,name=K,proto3" json:"K,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c0408b81072356a, []int{13}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Action) GetJ() string {
	if m != nil {
		return m.J
	}
	return ""
}

func (m *Action) GetK() string {
	if m != nil {
		return m.K
	}
	return ""
}

type Hit struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Attacker             string   `protobuf:"bytes,2,opt,name=attacker,proto3" json:"attacker,omitempty"`
	Victim               string   `protobuf:"bytes,3,opt,name=Victim,proto3" json:"Victim,omitempty"`
	AttackType           string   `protobuf:"bytes,4,opt,name=AttackType,proto3" json:"AttackType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hit) Reset()         { *m = Hit{} }
func (m *Hit) String() string { return proto.CompactTextString(m) }
func (*Hit) ProtoMessage()    {}
func (*Hit) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c0408b81072356a, []int{14}
}

func (m *Hit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hit.Unmarshal(m, b)
}
func (m *Hit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hit.Marshal(b, m, deterministic)
}
func (m *Hit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hit.Merge(m, src)
}
func (m *Hit) XXX_Size() int {
	return xxx_messageInfo_Hit.Size(m)
}
func (m *Hit) XXX_DiscardUnknown() {
	xxx_messageInfo_Hit.DiscardUnknown(m)
}

var xxx_messageInfo_Hit proto.InternalMessageInfo

func (m *Hit) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Hit) GetAttacker() string {
	if m != nil {
		return m.Attacker
	}
	return ""
}

func (m *Hit) GetVictim() string {
	if m != nil {
		return m.Victim
	}
	return ""
}

func (m *Hit) GetAttackType() string {
	if m != nil {
		return m.AttackType
	}
	return ""
}

type PlayerInfo struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PositionX            float32  `protobuf:"fixed32,2,opt,name=PositionX,proto3" json:"PositionX,omitempty"`
	PositionY            float32  `protobuf:"fixed32,3,opt,name=PositionY,proto3" json:"PositionY,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c0408b81072356a, []int{15}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *PlayerInfo) GetPositionX() float32 {
	if m != nil {
		return m.PositionX
	}
	return 0
}

func (m *PlayerInfo) GetPositionY() float32 {
	if m != nil {
		return m.PositionY
	}
	return 0
}

type Frame struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Cmd                  []int32  `protobuf:"varint,2,rep,packed,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Frame) Reset()         { *m = Frame{} }
func (m *Frame) String() string { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()    {}
func (*Frame) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c0408b81072356a, []int{16}
}

func (m *Frame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frame.Unmarshal(m, b)
}
func (m *Frame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frame.Marshal(b, m, deterministic)
}
func (m *Frame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frame.Merge(m, src)
}
func (m *Frame) XXX_Size() int {
	return xxx_messageInfo_Frame.Size(m)
}
func (m *Frame) XXX_DiscardUnknown() {
	xxx_messageInfo_Frame.DiscardUnknown(m)
}

var xxx_messageInfo_Frame proto.InternalMessageInfo

func (m *Frame) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Frame) GetCmd() []int32 {
	if m != nil {
		return m.Cmd
	}
	return nil
}

type SyncGear struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	StartTime            string   `protobuf:"bytes,2,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncGear) Reset()         { *m = SyncGear{} }
func (m *SyncGear) String() string { return proto.CompactTextString(m) }
func (*SyncGear) ProtoMessage()    {}
func (*SyncGear) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c0408b81072356a, []int{17}
}

func (m *SyncGear) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncGear.Unmarshal(m, b)
}
func (m *SyncGear) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncGear.Marshal(b, m, deterministic)
}
func (m *SyncGear) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncGear.Merge(m, src)
}
func (m *SyncGear) XXX_Size() int {
	return xxx_messageInfo_SyncGear.Size(m)
}
func (m *SyncGear) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncGear.DiscardUnknown(m)
}

var xxx_messageInfo_SyncGear proto.InternalMessageInfo

func (m *SyncGear) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *SyncGear) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

type JoinRoom struct {
	RoomID               int32    `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	UserID               int32    `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoom) Reset()         { *m = JoinRoom{} }
func (m *JoinRoom) String() string { return proto.CompactTextString(m) }
func (*JoinRoom) ProtoMessage()    {}
func (*JoinRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c0408b81072356a, []int{18}
}

func (m *JoinRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoom.Unmarshal(m, b)
}
func (m *JoinRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoom.Marshal(b, m, deterministic)
}
func (m *JoinRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoom.Merge(m, src)
}
func (m *JoinRoom) XXX_Size() int {
	return xxx_messageInfo_JoinRoom.Size(m)
}
func (m *JoinRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoom.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoom proto.InternalMessageInfo

func (m *JoinRoom) GetRoomID() int32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *JoinRoom) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type JoinRoomRes struct {
	Seed                 int64    `protobuf:"varint,1,opt,name=Seed,proto3" json:"Seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomRes) Reset()         { *m = JoinRoomRes{} }
func (m *JoinRoomRes) String() string { return proto.CompactTextString(m) }
func (*JoinRoomRes) ProtoMessage()    {}
func (*JoinRoomRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c0408b81072356a, []int{19}
}

func (m *JoinRoomRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomRes.Unmarshal(m, b)
}
func (m *JoinRoomRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomRes.Marshal(b, m, deterministic)
}
func (m *JoinRoomRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomRes.Merge(m, src)
}
func (m *JoinRoomRes) XXX_Size() int {
	return xxx_messageInfo_JoinRoomRes.Size(m)
}
func (m *JoinRoomRes) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomRes.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomRes proto.InternalMessageInfo

func (m *JoinRoomRes) GetSeed() int64 {
	if m != nil {
		return m.Seed
	}
	return 0
}

func init() {
	proto.RegisterType((*MoveUp)(nil), "proto.MoveUp")
	proto.RegisterType((*MoveDown)(nil), "proto.MoveDown")
	proto.RegisterType((*MoveDownOver)(nil), "proto.MoveDownOver")
	proto.RegisterType((*MoveLeft)(nil), "proto.MoveLeft")
	proto.RegisterType((*MoveLeftOver)(nil), "proto.MoveLeftOver")
	proto.RegisterType((*MoveRight)(nil), "proto.MoveRight")
	proto.RegisterType((*MoveRightOver)(nil), "proto.MoveRightOver")
	proto.RegisterType((*Fall)(nil), "proto.Fall")
	proto.RegisterType((*Die)(nil), "proto.Die")
	proto.RegisterType((*Idle)(nil), "proto.Idle")
	proto.RegisterType((*Bounce)(nil), "proto.Bounce")
	proto.RegisterType((*Props)(nil), "proto.Props")
	proto.RegisterType((*FootBoard)(nil), "proto.FootBoard")
	proto.RegisterType((*Action)(nil), "proto.Action")
	proto.RegisterType((*Hit)(nil), "proto.Hit")
	proto.RegisterType((*PlayerInfo)(nil), "proto.PlayerInfo")
	proto.RegisterType((*Frame)(nil), "proto.Frame")
	proto.RegisterType((*SyncGear)(nil), "proto.SyncGear")
	proto.RegisterType((*JoinRoom)(nil), "proto.JoinRoom")
	proto.RegisterType((*JoinRoomRes)(nil), "proto.JoinRoomRes")
}

func init() { proto.RegisterFile("jb.proto", fileDescriptor_8c0408b81072356a) }

var fileDescriptor_8c0408b81072356a = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0xcd, 0xaf, 0x93, 0x40,
	0x14, 0xc5, 0x03, 0x14, 0x02, 0xd7, 0xa7, 0x31, 0x2c, 0x0c, 0x31, 0xc6, 0xd4, 0x59, 0xd5, 0x8d,
	0x1b, 0x5d, 0x18, 0x13, 0x17, 0x7d, 0x21, 0x55, 0xfa, 0xfc, 0xa8, 0x53, 0x5a, 0x5b, 0x5d, 0x4d,
	0x61, 0x5a, 0x47, 0x81, 0x21, 0xc3, 0x58, 0xd3, 0xff, 0xde, 0xcc, 0x64, 0xfa, 0x61, 0xda, 0x95,
	0x99, 0xae, 0xe6, 0x9e, 0x7b, 0x39, 0xbf, 0x1c, 0x2e, 0x10, 0x20, 0xfc, 0xb9, 0x7a, 0xd1, 0x0a,
	0x2e, 0x79, 0xec, 0xeb, 0x03, 0xe5, 0x10, 0x7c, 0xe4, 0x5b, 0x3a, 0x6b, 0xe3, 0x07, 0xe0, 0x66,
	0x69, 0xe2, 0xf4, 0x9d, 0x81, 0x8f, 0xdd, 0x2c, 0x8d, 0x9f, 0x40, 0x34, 0xe1, 0x1d, 0x93, 0x8c,
	0x37, 0x8b, 0xc4, 0xed, 0x3b, 0x03, 0x17, 0x1f, 0x1b, 0xa7, 0xd3, 0x65, 0xe2, 0xfd, 0x3b, 0x5d,
	0xa2, 0x39, 0x84, 0x8a, 0x9a, 0xf2, 0x3f, 0x8d, 0x55, 0xee, 0x37, 0xb8, 0xd9, 0x73, 0x3f, 0x6f,
	0xa9, 0xb8, 0x46, 0xe6, 0x0f, 0x74, 0x2d, 0xaf, 0x91, 0x59, 0x71, 0xad, 0x67, 0xfe, 0x0a, 0x91,
	0x62, 0x63, 0xb6, 0xf9, 0x61, 0x37, 0xf4, 0x77, 0xb8, 0x7f, 0x00, 0x5b, 0x4f, 0x8d, 0xa1, 0x37,
	0x22, 0x55, 0x65, 0x95, 0xf9, 0x05, 0xbc, 0x94, 0x51, 0xdb, 0x31, 0xb3, 0xb2, 0xb2, 0xcb, 0xcc,
	0x21, 0xb8, 0xe5, 0xbf, 0x9b, 0xc2, 0x2e, 0xf5, 0x2d, 0xf8, 0x13, 0xc1, 0xdb, 0xee, 0x0c, 0xfa,
	0x10, 0xbc, 0x9c, 0x6c, 0x34, 0x2e, 0xc2, 0xaa, 0x8c, 0x63, 0xe8, 0x7d, 0x22, 0x35, 0xd5, 0x8c,
	0x08, 0xeb, 0x1a, 0x0d, 0x21, 0x1a, 0x71, 0x2e, 0x6f, 0x39, 0x11, 0xe5, 0x7f, 0x22, 0x5e, 0x41,
	0x30, 0x2c, 0x54, 0x98, 0x33, 0xff, 0x0d, 0x38, 0x63, 0xe3, 0x76, 0xc6, 0x4a, 0xdd, 0x19, 0xa3,
	0x73, 0x87, 0x18, 0x78, 0xef, 0xd9, 0xf9, 0x8b, 0xfb, 0x18, 0x42, 0x22, 0x25, 0x29, 0x7e, 0x51,
	0x61, 0x9c, 0x07, 0x1d, 0x3f, 0x82, 0x60, 0xce, 0x0a, 0xc9, 0x6a, 0x43, 0x31, 0x2a, 0x7e, 0x0a,
	0x30, 0xd4, 0xd7, 0xe4, 0xbb, 0x96, 0x26, 0x3d, 0x3d, 0x3b, 0xe9, 0xa0, 0x05, 0xc0, 0xa4, 0x22,
	0x3b, 0x2a, 0xb2, 0x66, 0xcd, 0xad, 0x2e, 0xff, 0x39, 0xf8, 0x23, 0x41, 0x6a, 0x7a, 0x69, 0x73,
	0x45, 0x5d, 0x26, 0x6e, 0xdf, 0x1b, 0xf8, 0x58, 0x95, 0xe8, 0x35, 0x84, 0xd3, 0x5d, 0x53, 0xbc,
	0xa3, 0xe4, 0xe2, 0x07, 0x35, 0x95, 0x44, 0xc8, 0x9c, 0xd5, 0xd4, 0xdc, 0xf5, 0xb1, 0x81, 0xde,
	0x40, 0x38, 0xe6, 0xac, 0xc1, 0x9c, 0xd7, 0x6a, 0x05, 0xea, 0x3c, 0xb8, 0x8d, 0x52, 0xfd, 0x59,
	0x47, 0x45, 0x96, 0x6a, 0xbb, 0x8f, 0x8d, 0x42, 0xcf, 0xe0, 0xde, 0xde, 0x8b, 0x69, 0xa7, 0x1e,
	0xdf, 0x94, 0xd2, 0x52, 0x9b, 0x3d, 0xac, 0xeb, 0x55, 0xa0, 0x7f, 0x06, 0x2f, 0xff, 0x06, 0x00,
	0x00, 0xff, 0xff, 0xcb, 0x97, 0xfb, 0xb8, 0x1f, 0x06, 0x00, 0x00,
}
